In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v1.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,24-12-2012,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,21-07-2011,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,18-09-2014,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,"Apr 10, 2013",10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,29-10-2014,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51370,17526,ES-2014-2057259,2/8/2014,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51371,36055,CA-2011-121573,3/11/2011,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51372,43576,TU-2011-9190,23-12-2011,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51373,22403,IN-2013-35388,7/8/2013,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51374,12513,ES-2011-1222857,30-09-2011,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [3]:
df['Order ID'].info()

<class 'pandas.Series'>
RangeIndex: 51375 entries, 0 to 51374
Series name: Order ID
Non-Null Count  Dtype
--------------  -----
51370 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [4]:
df['Order ID'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51370     True
51371     True
51372     True
51373     True
51374     True
Name: Order ID, Length: 51375, dtype: bool

In [16]:
df['Order ID'] = df['Order ID'].str.strip()

In [17]:
df['Order ID'].str.contains("")

0        True
1        True
2        True
3        True
4        True
         ...
51370    True
51371    True
51372    True
51373    True
51374    True
Name: Order ID, Length: 51375, dtype: bool

In [38]:
df[df['Order ID'].isna()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [22]:
df['Order ID'].isna().drop(columns='Order ID', inplace=True)

In [24]:
df.loc[df['Order ID'].isna(),'Order ID']

4837     NaN
12652    NaN
21844    NaN
23071    NaN
38711    NaN
Name: Order ID, dtype: str

In [27]:
df.loc[df['Order ID'].isna(),'Order ID'].drop(columns='Order ID', inplace=True)

In [31]:
df['Order ID'].dropna(inplace=True)

In [36]:
df[df['Order ID'].notna()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,24-12-2012,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,21-07-2011,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,18-09-2014,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,"Apr 10, 2013",10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,29-10-2014,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51370,17526,ES-2014-2057259,2/8/2014,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51371,36055,CA-2011-121573,3/11/2011,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51372,43576,TU-2011-9190,23-12-2011,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51373,22403,IN-2013-35388,7/8/2013,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51374,12513,ES-2011-1222857,30-09-2011,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [37]:
df = df[df['Order ID'].notna()]

In [43]:
df['Order ID'].str.contains(r"[^A-Za-z0-9-]",regex=True)

0        False
1        False
2        False
3        False
4        False
         ...
51370    False
51371    False
51372    False
51373    False
51374    False
Name: Order ID, Length: 51370, dtype: bool

In [40]:
df['Order ID']

0         CA-2012-169397
1         US-2011-144729
2        IT-2014-4749412
3           NI-2013-4420
4          IN-2014-14423
              ...
51370    ES-2014-2057259
51371     CA-2011-121573
51372       TU-2011-9190
51373      IN-2013-35388
51374    ES-2011-1222857
Name: Order ID, Length: 51370, dtype: str

In [44]:
df[df['Order ID'].str.contains(r"[^A-Za-z0-9-]",regex=True)]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [46]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v2.csv',index=False)