In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.7760,4,0.70,-13.84,0.79,Medium
1,6224,US-2011-144729,2011-07-21,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"Oic Paper Clips, Bulk Pack",11.5440,2,0.40,-5.22,0.97,Medium
2,15333,IT-2014-4749412,2014-09-18,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.8500,5,0.50,-4.80,3.71,Medium
3,49259,NI-2013-4420,2013-04-10,10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.3230,1,0.70,-3.09,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.17,0.00,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.5400,6,0.00,34.56,11.76,Medium
51366,36055,CA-2011-121573,2011-11-03,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phones,Panasonic Kx-Tg9471B,783.9600,4,0.00,219.51,64.42,High
51367,43576,TU-2011-9190,2011-12-23,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"Kitchenaid Blender, White",39.8400,1,0.60,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.66,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"Safco Bag Chairs, Black",169.2360,9,0.60,-182.03,17.34,High

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       50667 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   50387 non-null  str
 7   Segment         50675 non-null  str
 8   City            50728 non-null  str
 9   State           50383 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     10143 non-null  float64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        50550 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [4]:
df['Discount'].value_counts()

Discount
0.00    29106
0.20     4970
0.10     3989
0.40     3226
0.60     1987
0.70     1745
0.50     1598
0.17      727
0.47      715
0.15      534
0.27      380
0.30      335
0.45      320
0.80      315
0.25      196
0.07      149
0.35      121
0.37       69
0.32       27
0.65       17
0.57       12
0.55       10
0.85        2
Name: count, dtype: int64

In [9]:
df['Discount'].isna().sum()

np.int64(0)

In [8]:
df['Discount'] = df['Discount'].fillna(df['Discount'].median())

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   50387 non-null  str
 7   Segment         50675 non-null  str
 8   City            50728 non-null  str
 9   State           50383 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     10143 non-null  float64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [11]:
df['Ship Mode'].isna().sum()

np.int64(703)

In [18]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    30218
Second Class      10109
First Class        7377
Same Day           2640
Unknown             323
Name: count, dtype: int64

In [14]:
df['Ship Mode'] = df['Ship Mode'].str.lstrip().str.rstrip().str.title()

In [17]:
df['Ship Mode'] = df['Ship Mode'].replace(
    {
        '-':'Unknown',
        '?':'Unknown',
        'None':'Unknown',
        'Nan':'Unknown',
    }
)

In [22]:
df['Ship Mode'].isna().sum()

np.int64(0)

In [21]:
df['Ship Mode'] = df['Ship Mode'].fillna('Unknown')

In [24]:
df['Customer Name'].isna().sum()

np.int64(983)

In [27]:
df['Customer Name'].drop_duplicates()

0    Unknown
Name: Customer Name, dtype: str

In [26]:
df['Customer Name'] = 'Unknown'

In [28]:
df['Customer Name'] = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv', usecols=['Customer Name'])

In [41]:
df['Customer Name'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Customer Name
Non-Null Count  Dtype
--------------  -----
51370 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [32]:
df['Customer Name']

0          Joni Blumstein
1        Saphhira Shifley
2              Mick Brown
3           Michael Paige
4             Daniel Lacy
               ...
51365        Philip Brown
51366    Speros Goranitis
51367      Cari Macintyre
51368                 NaN
51369       Darren Powers
Name: Customer Name, Length: 51370, dtype: str

In [31]:
df['Customer Name'] = df['Customer Name'].str.lstrip().str.rstrip().str.title()

In [33]:
df['Customer Name'] == 'Unknown'

0        False
1        False
2        False
3        False
4        False
         ...
51365    False
51366    False
51367    False
51368    False
51369    False
Name: Customer Name, Length: 51370, dtype: bool

In [40]:
df[df['Customer Name'] == 'Nan']

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [35]:
df['Customer Name'].isna().sum()

np.int64(983)

In [36]:
df['Customer Name'] = df['Customer Name'].fillna('Unknown')

In [39]:
df['Customer Name'] = df['Customer Name'].replace('Nan','Unknown')

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   51370 non-null  str
 7   Segment         51370 non-null  str
 8   City            50728 non-null  str
 9   State           50383 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     10143 non-null  float64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [43]:
df['Segment'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Segment
Non-Null Count  Dtype
--------------  -----
50675 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [48]:
df['Customer Name'].value_counts()

Customer Name
Unknown            1505
Muhammed Yedwab     103
Steven Ward         101
Bill Eplett         101
Gary Hwang           99
                   ...
Brendan Dodson       32
Andy Reiter          32
Nicole Brennan       29
Michael Oakman       29
Darren Budd          28
Name: count, Length: 797, dtype: int64

In [45]:
df['Customer Name'] = df['Customer Name'].str.lstrip().str.rstrip().str.title()

In [47]:
df['Customer Name'] = df['Customer Name'].replace('?','Unknown')
df['Customer Name'] = df['Customer Name'].replace('-','Unknown')
df['Customer Name'] = df['Customer Name'].replace('Null','Unknown')
df['Customer Name'] = df['Customer Name'].replace('None','Unknown')

In [59]:
df['Segment'].isna().sum()

np.int64(0)

In [58]:
df['Segment'].drop_duplicates()

0       Consumer
1      Corporate
2        Unknown
9    Home Office
Name: Segment, dtype: str

In [52]:
df['Segment'] = df['Segment'].str.lstrip().str.rstrip().str.title()

In [55]:
df['Segment'] = df['Segment'].replace(
    {
        '-':'Unknown',
        '?':'Unknown',
        'None':'Unknown',
        'Nan':'Unknown',
    }
)

In [57]:
df['Segment'] = df['Segment'].fillna('Unknown')

In [83]:
df['City'].value_counts()

City
New York City      900
Unknown            791
Los Angeles        731
Philadelphia       526
San Francisco      496
                  ...
Charlottesville      1
Passau               1
Sagunto              1
Saint-Laurent        1
Zaoyang              1
Name: count, Length: 3632, dtype: int64

In [62]:
df['City'] = df['City'].str.lstrip().str.rstrip().str.title()

In [78]:
df[df['City'] == 'NaN']

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [75]:
df['City'] = df['City'].replace('Nan','Unknown')

In [82]:
df['City'].isna().sum()

np.int64(0)

In [81]:
df['City'] = df['City'].fillna('Unknown')

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   51370 non-null  str
 7   Segment         51370 non-null  str
 8   City            51370 non-null  str
 9   State           51370 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     51370 non-null  int64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(4), int64(3), str(17)
memory usage: 9.4 MB

In [86]:
df['State'] = df['State'].str.lstrip().str.rstrip().str.title()

In [97]:
df[df['State'] == 'Nan']

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [96]:
df['State'] = df['State'].replace('Nan','Unknown')

In [100]:
df['State'].isna().sum()

np.int64(0)

In [99]:
df['State'] = df['State'].fillna('Unknown')

In [108]:
df['Postal Code'].value_counts()

Postal Code
0        41483
10035      261
10009      226
10024      225
94122      203
         ...
38134        1
8302         1
84041        1
32935        1
27534        1
Name: count, Length: 632, dtype: int64

In [103]:
df['Postal Code'].isna().sum()

np.int64(41227)

In [105]:
df['Postal Code'] = df['Postal Code'].fillna(0)

In [107]:
df['Postal Code'] = df['Postal Code'].astype(int)

In [110]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv',index=False)