In [1]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\source\superstore_dirty.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518.0,CA-2012-169397,24-12-2012,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224.0,US-2011-144729,21-07-2011,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333.0,IT-2014-4749412,18-09-2014,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259.0,NI-2013-4420,"Apr 10, 2013",10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199.0,IN-2014-14423,29-10-2014,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,17526.0,ES-2014-2057259,2/8/2014,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51521,36055.0,CA-2011-121573,3/11/2011,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51522,43576.0,TU-2011-9190,23-12-2011,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51523,22403.0,IN-2013-35388,7/8/2013,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51524,12513.0,ES-2011-1222857,30-09-2011,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [15]:
df.shape

(51525, 24)

In [17]:
for cols in df.columns:
    print("df['"+cols+"']")

df['Row ID']
df['Order ID']
df['Order Date']
df['Ship Date']
df['Ship Mode']
df['Customer ID']
df['Customer Name']
df['Segment']
df['City']
df['State']
df['Country']
df['Postal Code']
df['Market']
df['Region']
df['Product ID']
df['Category']
df['Sub-Category']
df['Product Name']
df['Sales']
df['Quantity']
df['Discount']
df['Profit']
df['Shipping Cost']
df['Order Priority']

In [18]:
df['Row ID']

0        31518.0
1         6224.0
2        15333.0
3        49259.0
4        24199.0
          ...
51520    17526.0
51521    36055.0
51522    43576.0
51523    22403.0
51524    12513.0
Name: Row ID, Length: 51525, dtype: float64

In [19]:
df['Row ID'].drop_duplicates()

0        31518.0
1         6224.0
2        15333.0
3        49259.0
4        24199.0
          ...
51520    17526.0
51521    36055.0
51522    43576.0
51523    22403.0
51524    12513.0
Name: Row ID, Length: 51251, dtype: float64

In [25]:
#df.loc[df['Row ID'].drop_duplicates(),'Row ID']
df['Row ID'].isna().sum()

np.int64(0)

In [24]:
df['Row ID'] = df['Row ID'].fillna(df['Row ID'].ffill())

In [27]:
df.drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518.0,CA-2012-169397,24-12-2012,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224.0,US-2011-144729,21-07-2011,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333.0,IT-2014-4749412,18-09-2014,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259.0,NI-2013-4420,"Apr 10, 2013",10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199.0,IN-2014-14423,29-10-2014,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,17526.0,ES-2014-2057259,2/8/2014,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51521,36055.0,CA-2011-121573,3/11/2011,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51522,43576.0,TU-2011-9190,23-12-2011,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51523,22403.0,IN-2013-35388,7/8/2013,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51524,12513.0,ES-2011-1222857,30-09-2011,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [32]:
df = df[~df.duplicated()]

In [34]:
df[df.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 51375 entries, 0 to 51524
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51375 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       50667 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   50387 non-null  str
 7   Segment         50675 non-null  str
 8   City            50728 non-null  str
 9   State           50383 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     10143 non-null  float64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    50849 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  str
 19  Quantity        51370 non-null  str
 20  Discount        50645 non-null  str
 21  Profit          51370 non-null  str
 22  Shipping Cost   50649 non-null  str
 23  Order Priority  50293 non-null  str
dtypes: float64(1), int64(1), str(22)
memory usage: 9.8 MB

In [37]:
df['Row ID'].dtype

dtype('float64')

In [38]:
df['Row ID'].astype(int)

0        31518
1         6224
2        15333
3        49259
4        24199
         ...
51520    17526
51521    36055
51522    43576
51523    22403
51524    12513
Name: Row ID, Length: 51375, dtype: int64

In [39]:
df['Row ID'] = df['Row ID'].astype(int)

In [40]:
df['Row ID'].dtype

dtype('int64')

In [42]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v1.csv', index=False)